services:
  api:
    image: forex:production
    restart: always
    command: sh scripts/start_api.sh
    env_file:
      - ./../.env
    environment:
      - DJANGO_ENV=production
      - DJANGO_PORT=${DJANGO_PORT}
  cache:
    restart: always
    env_file:
      - ./../.env
    environment:
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - redisdata_production:/var/lib/redis/data
  db:
    restart: always
    env_file:
      - ./../.env
    volumes:
      - pgdata_production:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -d ${POSTGRES_DB} -U postgres
      interval: 10s
      timeout: 10s
      retries: 5
  worker:
    image: worker:production
    restart: always
    command: sh scripts/start_worker.sh
    environment:
      - DJANGO_ENV=production

volumes:
  pgdata_production:
    driver: local
    name: pgdata_production
  redisdata_production:
    driver: local
    name: redisdata_production
