services:
  api:
    image: forex:test
    restart: on-failure
    command: sh scripts/start_api.sh
    env_file:
      - ./../.env
    environment:
      - DJANGO_ENV=test
      - DJANGO_PORT=8000
    volumes:
      - ../scripts:/code/scripts
      - ../src:/code/src
      - ../tests:/code/tests
  cache:
    restart: on-failure
    env_file:
      - ./../.env
    environment:
      - REDIS_PORT=6379
    volumes:
      - redisdata_test:/var/lib/redis/data
  db:
    restart: on-failure
    env_file:
      - ./../.env
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -q -d forex_test -U postgres
      interval: 10s
      timeout: 10s
      retries: 5
  worker:
    image: worker:test
    restart: on-failure
    command: sh scripts/start_worker.sh
    env_file:
      - ./../.env
    environment:
      - DJANGO_ENV=test
    volumes:
      - ../scripts:/code/scripts
      - ../src:/code/src
      - ../tests:/code/tests

volumes:
  pgdata_test:
    driver: local
    name: pgdata_test
  redisdata_test:
    driver: local
    name: redisdata_test
