services:
  api:
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    container_name: forex_api
    ports:
      - ${DJANGO_PORT:-8000}:${DJANGO_PORT:-8000}
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
  cache:
    image: redis:7-alpine
    container_name: forex_cache
    ports:
      - ${REDIS_PORT:-6379}:${REDIS_PORT:-6379}
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 10s
      retries: 5
  db:
    image: postgres:17-alpine
    container_name: forex_db
    ports:
      - ${POSTGRES_PORT:-5432}:${POSTGRES_PORT:-5432}
  worker:
    build:
      context: ./..
      dockerfile: ./docker/Dockerfile
    container_name: forex_worker
    depends_on:
      db:
        condition: service_healthy
      cache:
        condition: service_healthy
